### ISSUE TITLE
Stuck in inventory

### ISSUE THREAD

**Issue by Jaccosf** [xDreamLand/dr-scratching#2]
Opening the scratch_ticket itself is working fine, but when it dissapears after you see what you've won, you can't do anything anymore and you'll be stuck in your inventory.

**Comment by Jaccosf** [comment]
Oh and, your discord link is invalid :/

**Comment by michieldesair** [comment]
Hi, thanks for downloading esx_dreamscratching, do you have the latest version?

**Comment by michieldesair** [comment]
> Oh and, your discord link is invalid :/

Made a new link, thanks!

**Comment by Jaccosf** [comment]
> Hi, thanks for downloading esx_dreamscratching, do you have the latest version?

Yes I do, also tested 1.2

**Comment by Jaccosf** [comment]
Solution: Add the scratch_ticket to the Config.CloseUiItems in esx_inventoryhud. Thanks for your help!
