### ISSUE TITLE
I dont get a Menu

### ISSUE THREAD

**Issue by GRRP-Timo** [xDreamLand/dr-scratching#6]
Hello, im Instaled the script add The Item etc. and use The item with esx_inventoryhud but i dont get the menu to scratch it. Can you help me pls

**Comment by michieldesair** [comment]
Hello. Never heard of this issue before. Can you please enable the debugMode and see if you get anything intresing in there? 

You can enable debugmode by typing the following in your server.cfg: `setr <resourcename>-debugMode 1`, so by default `setr dr-scratching-debugMode 1`

**Comment by Buttah426** [comment]
im having the same issue , where i cant scratch ticket , but comes up in the inventory, and i get a error on , 
 @dr-scratching/server/s_main.lua:40: attempt to call a nil value (field 'showNotification')

**Comment by JiminyKroket** [comment]
> 

You do not have a supported version of the ESX framework, specifically one that includes xPlayer.showNotification in the xPlayer table

**Comment by michieldesair** [comment]
Looks like a configuration issue. I'll mark this as solved. if you still have some issues please make a new issue, or join the Discord for support. https://discord.gg/wy4U5tdbJh
